{
    'name': 'Petty Cash Management',
    'version': '19.0.1.4.0',
    'summary': 'Petty cash floats, requests, approvals, payments and settlement',
    'category': 'Accounting/Accounting',
    'author': 'Ebin P G',
    'maintainer': 'Ebin P G',
    'website': 'https://www.arabiandentallab.com',
    'license': 'LGPL-3',
    'depends': ['account', 'mail', 'product'],
    'data': [
        'security/petty_cash_security.xml',
        'security/ir.model.access.csv',
        'data/ir_sequence_data.xml',
        'data/petty_cash_automation.xml',
        'data/petty_cash_server_actions.xml',
        'report/petty_cash_statement_report.xml',
        'views/petty_cash_allocation_views.xml',
        'views/petty_cash_transaction_views.xml',
        'views/petty_cash_expense_views.xml',
        'views/account_petty_cash_views.xml',
        'views/res_partner_views.xml',
        'views/account_move_line_views.xml',
        'wizard/petty_cash_close_wizard_views.xml',
        'views/petty_cash_dashboard_views.xml',
        'views/petty_cash_report_views.xml',
        'views/res_config_settings_views.xml',
        'views/petty_cash_menu.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'petty_cash/static/src/dashboard/petty_cash_dashboard.scss',
            'petty_cash/static/src/dashboard/petty_cash_dashboard.js',
            'petty_cash/static/src/dashboard/petty_cash_dashboard.xml',
        ],
    },
     'images': [
        'static/description/banner.png',
        'static/description/icon.png',
    ],
    'application': True,
    'installable': True,
}
