# -*- coding: utf-8 -*-
{
    'name': 'Lab Delivery',
    'version': '19.0.1.26.0',
    'summary': "Hand-delivery of finished lab work: who carries what where, and what happened (R4–R8)",
    'author': 'Ebin P G',
    'maintainer': 'Ebin P G',
    'category': 'Inventory/Delivery',
    'license': 'LGPL-3',
    'depends': ['lab_fieldwork', 'dynamic_filter_tiles', 'mrp'],
    'data': [
        'security/delivery_security.xml',
        'security/ir.model.access.csv',
        'data/ir_sequence.xml',
        'data/ir_cron.xml',
        'data/courier_data.xml',
        'views/courier_views.xml',
        'views/res_config_settings_views.xml',
        'views/stock_picking_views.xml',
        'views/delivery_views.xml',
        'views/sale_order_delivery_views.xml',
        'wizard/delivery_done_views.xml',
        'wizard/delivery_new_views.xml',
        'wizard/delivery_receive_views.xml',
        'views/menus.xml',
        'data/filter_tiles.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'lab_delivery/static/src/scss/my_day_delivery.scss',
            'lab_delivery/static/src/js/photo_barcode.js',
            'lab_delivery/static/src/js/scan_station.js',
            'lab_delivery/static/src/js/my_day_delivery.js',
            'lab_delivery/static/src/xml/scan_station.xml',
            'lab_delivery/static/src/xml/my_day_delivery.xml',
            'lab_delivery/static/src/scss/receipt_scan.scss',
            'lab_delivery/static/src/js/receipt_scan_field.js',
            'lab_delivery/static/src/xml/receipt_scan_field.xml',
        ],
    },
    'installable': True,
    'application': False,
}
